n_latents: 1
d_model: 512
n_heads: 8
d_mlp: 1024
dropout: 0.1
scale_exponent: -0.25
return_latents: mean_pool
n_blocks: 2
tasks:
  - key: eyes
    n_classes: 2
data_config:
  n_channels: 64
  max_sr: 180
  min_sr: 180
  f_min: 2
