dtype: bf16
dataset_path: /teamspace/uploads/eeg-motor-movement-imagery
num_epochs: 15
batch_size: 32
train_micro_batch_size: 8
val_micro_batch_size: 32
validation_interval: 1.0
log_interval: 1
max_lr: 0.0001
lr_schedules:
  - start: 0.0
    type: linear
    kargs:
      start_factor: 0.0000001
      end_factor: 1.0
  # - start: 0.025
  #   type: exponential
  #   kargs:
  #     gamma: 0.1
  - start: 0.05
    type: cosine
    kargs:
      eta_min: 0.0
  # - start: 0.25
  #   type: constant
  #   kargs:
  #     factor: 1.0
  # - start: 0.5
  #   type: cosine
  #   kargs:
  #     eta_min: 0.0
weight_decay: 0.01
grad_clip: 1.0
