n_latents: 1
d_model: 512
n_heads: 8
d_mlp: 1024
dropout: 0.1
scale_exponent: -0.25
return_latents: mean_pool
n_blocks: 2
tasks:
  - key: eyes
    n_classes: 2
data_config:
  channel_counts:
    - 5
    - 8
    - 64
  sampling_rates:
    - 128
    - 128
    - 180
  f_min: 2
  f_max: 20
  kernel_sec: 0.5
  sequence_length_seconds: 1.0
