dtype: bf16
ds_labels_map:
    base_eyes_open: 0
    base_eyes_closed: 1
ds_tasks_map:
    move_eyes_open: 0
    move_eyes_closed: 0
ds_split_configs:
  - split_name: lemon_resting_eyes_val 
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/EEG_MPILMBB_LEMON/EEG_Raw_BIDS_ID"
    output_path: "./data/lemon_rs"
    subjects: [10246, 10247, 10252, 10265, 10272, 10021, 10024, 10282, 10283, 10028, 10026, 10032, 10163, 10295, 10170, 10300, 10048, 10056, 10318, 10192, 10194, 10199, 10075, 10077, 10080, 10213, 10216, 10220, 10227, 10239]
    sessions: [1]
    channel_mask: None
    data_source: lemon_rest
    headset: lemon_62
    sampling_rate: 250
    epoch_length_sec: 5.0
    resample_sfreq: 250.0
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/EEG_MPILMBB_LEMON/EEG_Raw_BIDS_ID"
    output_path: "./data/lemon_rs"
    subjects: [10240, 10241, 10242, 10243, 10244, 10245, 10248, 10249, 10250, 10251, 10254, 10255, 10256, 10257, 10258, 10260, 10261, 10262, 10263, 10264, 10266, 10267, 10268, 10269, 10270, 10271, 10273, 10274, 10275, 10276, 10277, 10278, 10279, 10280, 10284, 10285, 10286, 10287, 10288, 10289, 10290, 10291, 10292, 10294, 10296, 10297, 10298, 10299, 10301, 10302, 10303, 10304, 10305, 10306, 10307, 10308, 10309, 10310, 10311, 10314, 10315, 10316, 10317, 10319, 10321, 10002, 10003, 10004, 10005, 10006, 10007, 10010, 10012, 10015, 10016, 10017, 10019, 10020, 10022, 10023, 10027, 10029, 10030, 10031, 10033, 10034, 10035, 10036, 10037, 10038, 10039, 10040, 10041, 10042, 10044, 10045, 10046, 10047, 10049, 10050, 10051, 10052, 10053, 10059, 10060, 10061, 10062, 10063, 10064, 10065, 10066, 10067, 10068, 10069, 10070, 10071, 10072, 10073, 10074, 10076, 10078, 10079, 10081, 10083, 10084, 10085, 10086, 10087, 10088, 10089, 10090, 10091, 10092, 10093, 10094, 10100, 10104, 10126, 10134, 10136, 10137, 10138, 10141, 10142, 10146, 10148, 10150, 10152, 10155, 10157, 10162, 10164, 10165, 10166, 10168, 10176, 10183, 10191, 10193, 10195, 10196, 10197, 10200, 10201, 10202, 10203, 10204, 10207, 10210, 10214, 10215, 10218, 10219, 10222, 10223, 10224, 10226, 10228, 10230, 10231, 10232, 10233, 10234, 10236, 10238]
    sessions: [1]
    channel_mask: None
    data_source: lemon_rest
    headset: lemon_62
    sampling_rate: 250
    epoch_length_sec: 5.0
    resample_sfreq: 250.0
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/eeg-motor-movement-imagery"
    output_path: "./data/eeg_mmi"
    subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
    sessions: [1, 2]
    channel_mask: None
    data_source: eeg_mmi
    headset: physionet_64
    epoch_length_sec: 5.0
    sampling_rate: 160
  - split_name: eeg_mmi_eyes_val
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/eeg-motor-movement-imagery"
    output_path: "./data/eeg_mmi"
    subjects: [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
    sessions: [1, 2]
    channel_mask: None
    data_source: eeg_mmi
    headset: physionet_64
    epoch_length_sec: 5.0
    sampling_rate: 160
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/emotiv-alpha-crowd/epoc"
    output_path: "./data/emotiv_alpha"
    subjects: [2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13]
    sessions: [1]
    channel_mask: None
    data_source: emotive_alpha
    headset: emotiv_epoc_14
    epoch_length_sec: 5.0
    sampling_rate: 128
  - split_name: emotiv_alpha_eyes_val
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/emotiv-alpha-crowd/epoc"
    output_path: "./data/emotiv_alpha"
    subjects: [1,7]
    sessions: [1]
    channel_mask: None
    data_source: emotive_alpha
    headset: emotiv_epoc_14
    epoch_length_sec: 5.0
    sampling_rate: 128
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/emotiv-alpha-crowd/insight"
    output_path: "./data/emotiv_alpha"
    subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    sessions: [1]
    channel_mask: None
    data_source: emotive_alpha
    headset: emotiv_insight_5
    epoch_length_sec: 5.0
    sampling_rate: 128
  - split_name: emotiv_alpha_eyes_val
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/emotiv-alpha-crowd/insight"
    output_path: "./data/emotiv_alpha"
    subjects: [12,13,14]
    sessions: [1]
    channel_mask: None
    data_source: emotive_alpha
    headset: emotiv_insight_5
    epoch_length_sec: 5.0
    sampling_rate: 128
num_epochs: 10
batch_size: 64
train_micro_batch_size: 8
val_micro_batch_size: 64
validation_interval: 1.0
log_interval: 1
max_lr: 0.0001
lr_schedules:
  - start: 0.0
    type: linear
    kargs:
      start_factor: 0.0000001
      end_factor: 1.0
  # - start: 0.025
  #   type: exponential
  #   kargs:
  #     gamma: 0.1
  # - start: 0.05
  #   type: cosine
  #   kargs:
  #     eta_min: 0.0
  - start: 0.10
    type: constant
    kargs:
      factor: 1.0
  - start: 0.5
    type: cosine
    kargs:
      eta_min: 0.0
weight_decay: 0.01
grad_clip: 1.0
