dtype: bf16
ds_labels_map:
    base_eyes_open: 0
    base_eyes_closed: 1
ds_tasks_map:
    move_eyes_open: 0
    move_eyes_closed: 0
ds_split_configs:
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/eeg-motor-movement-imagery"
    output_path: "./data/eeg_mmi"
    subjects: ["S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008", "S009", "S010", "S011", "S012", "S013", "S014", "S015", "S016", "S017", "S018", "S019", "S020", "S021", "S022", "S023", "S024", "S025", "S026", "S027", "S028", "S029", "S030", "S031", "S032", "S033", "S034", "S035", "S036", "S037", "S038", "S039", "S040", "S041", "S042", "S043", "S044", "S045", "S046", "S047", "S048", "S049", "S050", "S051", "S052", "S053", "S054", "S055", "S056", "S057", "S058", "S059", "S060", "S061", "S062", "S063", "S064", "S065", "S066", "S067", "S068", "S069", "S070", "S071", "S072", "S073", "S074", "S075", "S076", "S077", "S078", "S079", "S080", "S081", "S082", "S083", "S084", "S085", "S086", "S087", "S088", "S089", "S090", "S091", "S092", "S093", "S094", "S095", "S096", "S097", "S098", "S099"]
    sessions: ["R01", "R02"]
    channel_mask: None
    data_source: eeg_mmi
    headset: physionet_64
    epoch_length_sec: 5.0
    sampling_rate: 160
  - split_name: eeg_mmi_eyes_val
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/eeg-motor-movement-imagery"
    output_path: "./data/eeg_mmi"
    subjects: ["S100", "S101", "S102", "S103", "S104", "S105", "S106", "S107", "S108", "S109"]
    sessions: ["R01", "R02"]
    channel_mask: None
    data_source: eeg_mmi
    headset: physionet_64
    epoch_length_sec: 5.0
    sampling_rate: 160
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/emotiv-alpha-crowd/epoc"
    output_path: "./data/emotiv_alpha"
    subjects: ["S002", "S003", "S004", "S005", "S006", "S008", "S009", "S010", "S011", "S012", "S013"]
    sessions: [1]
    channel_mask: None
    data_source: emotive_alpha
    headset: emotiv_epoc_14
    epoch_length_sec: 5.0
    sampling_rate: 128
  - split_name: emotiv_alpha_epoch_eyes_val
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/emotiv-alpha-crowd/epoc"
    output_path: "./data/emotiv_alpha"
    subjects: ["S001", "S007"]
    sessions: [1]
    channel_mask: None
    data_source: emotive_alpha
    headset: emotiv_epoc_14
    epoch_length_sec: 5.0
    sampling_rate: 128
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/emotiv-alpha-crowd/insight"
    output_path: "./data/emotiv_alpha"
    subjects: ["S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008", "S009", "S010", "S011"]
    sessions: [1]
    channel_mask: None
    data_source: emotive_alpha
    headset: emotiv_insight_5
    epoch_length_sec: 5.0
    sampling_rate: 128
  - split_name: emotiv_alpha_insight_eyes_val
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/emotiv-alpha-crowd/insight"
    output_path: "./data/emotiv_alpha"
    subjects: ["S012", "S013", "S014"]
    sessions: [1]
    channel_mask: None
    data_source: emotive_alpha
    headset: emotiv_insight_5
    epoch_length_sec: 5.0
    sampling_rate: 128
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/neurotechs"
    output_path: "./data/neurotechs"
    subjects: ['sub-21e',  'sub-24e',  'sub-24c',  'sub-06e',  'sub-11c',  'sub-08c',  'sub-42e',  'sub-15e',  'sub-26e',  'sub-15c',  'sub-05e',  'sub-22e',  'sub-41e',  'sub-16e',  'sub-40e',  'sub-01e',  'sub-02c',  'sub-19c',  'sub-27e',  'sub-03c',  'sub-23e',  'sub-10c',  'sub-17e',  'sub-21c',  'sub-22c',  'sub-14c',  'sub-16c',  'sub-04e',  'sub-31e',  'sub-06c',  'sub-10e',  'sub-19e',  'sub-11e',  'sub-25e',  'sub-18e',  'sub-36e',  'sub-12c',  'sub-09e',  'sub-07e',  'sub-12e',  'sub-07c',  'sub-28e',  'sub-23c',  'sub-33e',  'sub-29e',  'sub-20c',  'sub-39e',  'sub-08e',  'sub-18c',  'sub-04c',  'sub-38e',  'sub-03e',  'sub-34e',  'sub-01c',  'sub-13e']   
    sessions: ['ses-1', 'ses-2']
    channel_mask: None
    data_source: neurotechs
    headset: "unicorn_hybrid_black_8"
    epoch_length_sec: 5.0
    sampling_rate: 250
  - split_name: neurotechs_eyes_val
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/neurotechs"
    output_path: "./data/neurotechs"
    subjects: ['sub-02e',  'sub-37e',  'sub-43e',  'sub-20e',  'sub-13c',  'sub-14e',  'sub-05c',  'sub-09c'] 
    sessions: ['ses-1', 'ses-2']
    channel_mask: None
    data_source: neurotechs
    headset: "unicorn_hybrid_black_8"
    epoch_length_sec: 5.0
    sampling_rate: 250
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/resting-eeg-study-methods"
    output_path: "./data/resting_eeg"
    subjects: ["sub-01", "sub-02", "sub-03", "sub-04", "sub-05", "sub-06", "sub-07", "sub-08", "sub-09", "sub-10", "sub-11", "sub-12", "sub-13", "sub-14", "sub-15", "sub-16", "sub-17", "sub-18", "sub-19", "sub-20", "sub-21", "sub-22"]
    sessions: ["pre"]
    channel_mask: None
    data_source: resting_methods
    headset: brain_actichamp_31
    epoch_length_sec: 5.0
    sampling_rate: 500
  - split_name: resting_eeg_eyes_val
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/resting-eeg-study-methods"
    output_path: "./data/resting_eeg"
    subjects: ["sub-20", "sub-21", "sub-22"]
    sessions: ["pre"]
    channel_mask: None
    data_source: resting_methods
    headset: brain_actichamp_31
    epoch_length_sec: 5.0
    sampling_rate: 500
  - split_name: lemon_resting_eyes_val 
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/EEG_MPILMBB_LEMON/EEG_Raw_BIDS_ID"
    output_path: "./data/lemon_rs"
    subjects: ["sub-010246", "sub-010247", "sub-010252", "sub-010265", "sub-010272", "sub-010021", "sub-010024", "sub-010282", "sub-010283", "sub-010028", "sub-010026", "sub-010032", "sub-010163", "sub-010295", "sub-010170", "sub-010300", "sub-010048", "sub-010056", "sub-010318", "sub-010192", "sub-010194", "sub-010199", "sub-010075", "sub-010077", "sub-010080", "sub-010213", "sub-010216", "sub-010220", "sub-010227", "sub-010239"]
    sessions: [1]
    channel_mask: None
    data_source: lemon_rest
    headset: lemon_62
    sampling_rate: 250
    epoch_length_sec: 5.0
    resample_sfreq: 250.0
  - split_name: train
    source_base_path: "/teamspace/gcs_connections/neural-decode-data/EEG_MPILMBB_LEMON/EEG_Raw_BIDS_ID"
    output_path: "./data/lemon_rs"
    subjects: ["sub-010240", "sub-010241", "sub-010242", "sub-010243", "sub-010244", "sub-010245", "sub-010248", "sub-010249", "sub-010250", "sub-010251", "sub-010254", "sub-010255", "sub-010256", "sub-010257", "sub-010258", "sub-010260", "sub-010261", "sub-010262", "sub-010263", "sub-010264", "sub-010266", "sub-010267", "sub-010268", "sub-010269", "sub-010270", "sub-010271", "sub-010273", "sub-010274", "sub-010275", "sub-010276", "sub-010277", "sub-010278", "sub-010279", "sub-010280", "sub-010284", "sub-010285", "sub-010286", "sub-010287", "sub-010288", "sub-010289", "sub-010290", "sub-010291", "sub-010292", "sub-010294", "sub-010296", "sub-010297", "sub-010298", "sub-010299", "sub-010301", "sub-010302", "sub-010303", "sub-010304", "sub-010305", "sub-010306", "sub-010307", "sub-010308", "sub-010309", "sub-010310", "sub-010311", "sub-010314", "sub-010315", "sub-010316", "sub-010317", "sub-010319", "sub-010321", "sub-010002", "sub-010003", "sub-010004", "sub-010005", "sub-010006", "sub-010007", "sub-010010", "sub-010012", "sub-010015", "sub-010016", "sub-010017", "sub-010019", "sub-010020", "sub-010022", "sub-010023", "sub-010027", "sub-010029", "sub-010030", "sub-010031", "sub-010033", "sub-010034", "sub-010035", "sub-010036", "sub-010037", "sub-010038", "sub-010039", "sub-010040", "sub-010041", "sub-010042", "sub-010044", "sub-010045", "sub-010046", "sub-010047", "sub-010049", "sub-010050", "sub-010051", "sub-010052", "sub-010053", "sub-010059", "sub-010060", "sub-010061", "sub-010062", "sub-010063", "sub-010064", "sub-010065", "sub-010066", "sub-010067", "sub-010068", "sub-010069", "sub-010070", "sub-010071", "sub-010072", "sub-010073", "sub-010074", "sub-010076", "sub-010078", "sub-010079", "sub-010081", "sub-010083", "sub-010084", "sub-010085", "sub-010086", "sub-010087", "sub-010088", "sub-010089", "sub-010090", "sub-010091", "sub-010092", "sub-010093", "sub-010094", "sub-010100", "sub-010104", "sub-010126", "sub-010134", "sub-010136", "sub-010137", "sub-010138", "sub-010141", "sub-010142", "sub-010146", "sub-010148", "sub-010150", "sub-010152", "sub-010155", "sub-010157", "sub-010162", "sub-010164", "sub-010165", "sub-010166", "sub-010168", "sub-010176", "sub-010183", "sub-010191", "sub-010193", "sub-010195", "sub-010196", "sub-010197", "sub-010200", "sub-010201", "sub-010202", "sub-010203", "sub-010204", "sub-010207", "sub-010210", "sub-010214", "sub-010215", "sub-010218", "sub-010219", "sub-010222", "sub-010223", "sub-010224", "sub-010226", "sub-010228", "sub-010230", "sub-010231", "sub-010232", "sub-010233", "sub-010234", "sub-010236", "sub-010238"]
    sessions: [1]
    channel_mask: None
    data_source: lemon_rest
    headset: lemon_62
    sampling_rate: 250
    epoch_length_sec: 5.0
    resample_sfreq: 250.0
num_epochs: 10
batch_size: 64
train_micro_batch_size: 8
val_micro_batch_size: 64
validation_interval: 0.25
log_interval: 1
max_lr: 0.0001
lr_schedules:
  - start: 0.0
    type: linear
    kargs:
      start_factor: 0.0000001
      end_factor: 1.0
  # - start: 0.025
  #   type: exponential
  #   kargs:
  #     gamma: 0.1
  # - start: 0.05
  #   type: cosine
  #   kargs:
  #     eta_min: 0.0
  - start: 0.025
    type: constant
    kargs:
      factor: 1.0
  - start: 0.5
    type: cosine
    kargs:
      eta_min: 0.0
weight_decay: 0.01
grad_clip: 1.0
