n_latents: 1
d_model: 256
n_heads: 4
d_mlp: 512
dropout: 0.1
scale_exponent: -0.25
return_latents: middle 
n_blocks: 2
epsilon_max: 0.1
data_config:
  n_channels: 306
  max_sr: 250
  min_sr: 250
  f_min: 2.5
