n_latents: 1
d_model: 64
n_heads: 4
d_mlp: 128
rope_dim: 8
dropout: 0.1
scale_exponent: -0.25
return_latents: all
n_blocks: 1
tasks:
  - key: move_eyes
    index: 0
    labels_map:
      eyes_open: 0
      eyes_closed: 1
  - key: move_image_left_right_fist_both_fist_feet
    index: 1
    labels_map:
      rest: 0
      move_left_fist: 1
      move_right_fist: 2
      move_both_fist: 3
      move_both_feet: 4
      imag_left_fist: 5
      imag_right_fist: 6
      imag_both_fist: 7
      imag_both_feet: 8
data_config:
  f_min: 0.5
  f_max: 60
  kernel_sec: 2.5
  sequence_length_seconds: 5.0
  position_index_per_second: 512

