dtype: bf16
dataset_path: /teamspace/uploads/vss/
num_epochs: 10
batch_size: 32
train_micro_batch_size: 4
val_micro_batch_size: 16
validation_interval: 1.0
log_interval: 1
max_lr: 0.0001
weight_decay: 0.01
warmup_frac: 0.05
grad_clip: 1.0
